-- Drop the table first (if it exists)
drop table if exists public.projects cascade;

-- Drop the enum type if it already exists
drop type if exists public.current_status cascade;

-- Create the enum type
create type public.current_status as enum ('in-progress', 'completed');

-- Create the table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  slug text not null unique,
  status public.current_status not null default 'in-progress',
  collaborators jsonb not null default '[]'::jsonb
);
